### ISSUE TITLE
Our layout for tab 1 and 2 are slightly larger than screen size, forcing users to scroll. 

### ISSUE THREAD

**Issue by gavingro** [ubco-mds-2021-labs/dashboard1-group-a#35]
The user experience would be smoother if we could adjust the layout/size of our plots and tabs so that everything was visible without forcing the user to scroll.

**Comment by DishaDH123** [comment]
presently resolved the issue for tab1 by making layout changes to layout and the plot. Will further resolve it for tab2 once the tab2 layout is finalized.
