### ISSUE TITLE
Our plots (with y-axis ranges to 0) may not allow us to view granular differences at higher values.

### ISSUE THREAD

**Issue by gavingro** [ubco-mds-2021-labs/dashboard1-group-a#36]
It is a good idea to keep our y-axis ranges scaling from 0 up to our observed values.

However, it would also be able to to view the smaller differences between lines of different categories at higher values 
(eg. Temperature differences between Functional Space and Living Areas are hard to view).

We might be able to allow users to select specific subsets or views of the data by making the plots interactive, without needing additional controls on our overall dashboard.

We could try to use `figure.interactive().to_html()` instead of `figure.to_html()` as a first step.

**Comment by DishaDH123** [comment]
Added interactive element to the plots and now the graphs can be zoomed for all the line graphs and can be hovered upon for the box plots.
