### ISSUE TITLE
Gaps between "Daytime/Nighttime" on hour-of-the-day categories.

### ISSUE THREAD

**Issue by gavingro** [ubco-mds-2021-labs/dashboard1-group-a#38]
They may be explainable and reasonable, but they are confusing to a user.

We could add in a popup explaining the gaps (due to aggregation) and how the data is aggregated/resampled.

(or we could add in a datapoint for that specific view?)

**Comment by DishaDH123** [comment]
Resolved making box plot for this particular categories instead of line plot which explains the average of temperatures and humidity for varied number of data more explicitly. The gap occurred due to the way the data was divided in the hour of the day.
